[options]
admin_passwd = ${ODOO_ADMIN_PASSWORD:admin}

db_host = ${DB_HOST:localhost}
db_port = ${DB_PORT:5432}
db_user = ${DB_USER:odoo}
db_password = ${DB_PASSWORD:odoo}
db_name = ${DB_NAME:odoo}
db_sslmode = ${DB_SSLMODE:prefer}

addons_path = /mnt/extra-addons/odoo_position_integration,/usr/lib/python3/dist-packages/odoo/addons

http_port = 8069
http_interface = 0.0.0.0
workers = 0
log_level = info
